spring.application.name=missinggl
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.maximum-pool-size=5

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.postgresql=DEBUG

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB