apiVersion: v1
kind: Secret
metadata:
  name: synmetrix-secrets
type: Opaque
stringData:
  DB_PASSWORD: "A#1h@*kmc7pwc-db"
  CUBEJS_DB_PASS: "A#1h@*kmc7pwc-db"
  CUBEJS_API_SECRET: "your-secret-key-change-in-production"
