FROM node:20-alpine AS build
ARG WORK_DIR
WORKDIR /app
ENV NODE_OPTIONS "--max-old-space-size=4096"
ENV NPM_CONFIG_PREFIX=/tmp/.npm-global
ENV PATH=$PATH:/tmp/.npm-global/bin
ENV HOME=/tmp

# copy the project files
COPY ${WORK_DIR} .
RUN npm config set registry https://registry.npmmirror.com/ --global
RUN npm install
RUN npm run build --prod

# Create runtime image
FROM nginx:mainline-alpine
ENV WEB_DIR=/var/web/mis-dashboard

RUN mkdir -p ${WEB_DIR}

COPY --from=build /app/build ${WEB_DIR}/
COPY --from=build /app/docker/nginx.conf /etc/nginx/conf.d/default.conf
